version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: spotify_mysql
    # Aumentei o tempo de conexão para evitar queda durante a migração
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=64M --wait_timeout=28800 --interactive_timeout=28800 --net_read_timeout=3600 --net_write_timeout=3600
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: spotify_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Testar Docker para testar se o banco está funcionando antes de iniciar o Metabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20  

  metabase:
    image: metabase/metabase
    container_name: spotify_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: spotify_db
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: db
      MB_DB_CONNECTION_TIMEOUT_MS: 3000000
    depends_on:
      db:
        condition: service_healthy # Para iniciar apenas quando o db estiver saudável

volumes:
  db_data: